Massive reorg for chrooted operation
After today's CVE, I went whole hog to limit potential abuse
of bind by third parties.

diff --git a/net/bind-latest/files/named.init b/net/bind-latest/files/named.init
--- a/net/bind-latest/files/named.init
+++ b/net/bind-latest/files/named.init
@@ -1,37 +1,27 @@
 #!/bin/sh /etc/rc.common
 # Since we are running from xinetd, we just kick bind
 
-START=50
+START=48
+STOP=48
+
 CHRT=/etc/chroot/bind/
 
-config_file=$CHRT/etc/bind/named.conf
 pid_file=$CHRT/var/run/named/named.pid
 
-# It would be easier on flash if we only did this part once
-
-setup_jail() {
-mkdir -p $CHRT/dev $CHRT/tmp 
-mount $CHRT/tmp
-
-cp -a /dev/zero /dev/urandom /dev/random /dev/null $CHRT/dev
-
-}
-
 start() {
-  
-  if [ -e $pid_file ]
-  then
-     echo "  named already running with PID `cat $pid_file`"
-     return 1
-  fi
-  echo Kicking isc-bind in xinetd
 
-  nslookup 127.255.255.255 127.0.0.1
-
-  if [ $? -ne 0 ]
+    echo Kicking isc-bind in xinetd
+    /usr/sbin/named.montime &
+    nslookup ::1 ::1 > /dev/null
+    if [ $? -ne 0 ]
   then
     echo "  isc-bind failed to start"
+    logger " isc-bind failed to start "
   fi
+  else 
+    logger " isc-bind started "
+  fi
+
 }
 
 stop() {
@@ -44,11 +34,12 @@ stop() {
     then
       echo "  PID " `cat $pid_file` not found
       echo "  Is the named server running?"
-    fi
+   fi
 
     rm -f $pid_file
 
     else
-    echo "  $pid_file not found"
+    echo "  $pid_file not found, trying brute force "
+    killall named
   fi
 }
